//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationppp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Addresses = new HashSet<Address>();
            this.Companies = new HashSet<Company>();
            this.Neighbourhoods = new HashSet<Neighbourhood>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Neighbourhood Neighbourhood { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Neighbourhood> Neighbourhoods { get; set; }
    }
}
