//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationppp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Salons = new HashSet<Salon>();
        }
    
        public int AddressID { get; set; }
        public int AddressType { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Entrance { get; set; }
        public string Flat { get; set; }
        public string Apartment { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> NeighbourhoodID { get; set; }
        public string AddressText { get; set; }
    
        public virtual City City { get; set; }
        public virtual Neighbourhood Neighbourhood { get; set; }
        public virtual ICollection<Salon> Salons { get; set; }
    }
}
