//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationppp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbourhood
    {
        public Neighbourhood()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int NeighbourhoodID { get; set; }
        public int CityID { get; set; }
        public string NeighbourhoodName { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
