//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationppp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonsMainScreenMobile
    {
        public int SalonID { get; set; }
        public string SalonName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string Apartment { get; set; }
        public string Entrance { get; set; }
        public string Flat { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public Nullable<double> Rating { get; set; }
        public string CityName { get; set; }
        public string NeighbourhoodName { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> NeighbourhoodID { get; set; }
        public string CreateBy { get; set; }
        public bool VisibleForUsers { get; set; }
    }
}
