//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapaziMi.DAL.Entities.ZapaziMiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonDetailsInfo
    {
        public int SalonID { get; set; }
        public string SalonName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string SiteUrl { get; set; }
        public string CityName { get; set; }
        public string NeighbourhoodName { get; set; }
        public string Apartment { get; set; }
        public string Entrance { get; set; }
        public string Flat { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Phones { get; set; }
        public string Emails { get; set; }
        public Nullable<int> ServicesCount { get; set; }
    }
}
